---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wildwatch/public_html/penguin-api
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp website/*.php $DEPLOYPATH/
    - /bin/cp website/*.sql $DEPLOYPATH/
