<Project>
  <PropertyGroup>
    <KeystorePassword>zMwiz2WS5WjZ2Gq2b8GZPnZT</KeystorePassword>
    <SigningKeyPassword>zMwiz2WS5WjZ2Gq2b8GZPnZT</SigningKeyPassword>
    <BoxTagsApiUrl>https://wildwatch.co.nz/api/boxtags.php</BoxTagsApiUrl>
    <BoxTagsApiKey>tJcyrnfhZht3a4oSUQt1JIB09f2MXBaf</BoxTagsApiKey>
  </PropertyGroup>
</Project>
