package nz.co.penguinmonitor.model

data class BirdCsvRowData(
    val number: String = "",
    val scannedId: String = "",
    val chipDate: String = "",
    val sex: String = "",
    val vidForScanner: String = "",
    val plusBoxes: String = "",
    val chipBox: String = "",
    val breedBox2021: String = "",
    val breedBox2022: String = "",
    val breedBox2023: String = "",
    val breedBox2024: String = "",
    val breedBox2025: String = "",
    val lastKnownLifeStage: String = "",
    val nestSuccess2021: String = "",
    val reClutch21: String = "",
    val nestSuccess2022: String = "",
    val reClutch22: String = "",
    val nestSuccess2023: String = "",
    val reClutch23: String = "",
    val nestSuccess2024: String = "",
    val reClutch24: String = "",
    val chipBy: String = "",
    val chipAs: String = "",
    val chipOk: String = "",
    val chipWeight: String = "",
    val flipperLength: String = "",
    val persistence: String = "",
    val alarmsScanner: String = "",
    val wasSingle: String = "",
    val chickSizeSex: String = "",
    val chickReturnDate: String = "",
    val reChip: String = "",
    val reChipBy: String = "",
    val activeChip2: String = "",
    val rechipDate: String = "",
    val fullIso15Digits: String = "",
    val solo: String = "",
    val kommentar: String = ""
)
